services:


    marvin255_jwt_symfony.builder:
        class: Marvin255\Jwt\Builder\Builder
        shared: false
    Marvin255\Jwt\JwtBuilder:
        alias: marvin255_jwt_symfony.builder


    marvin255_jwt_symfony.encoder:
        class: Marvin255\Jwt\Encoder\Encoder
    Marvin255\Jwt\JwtEncoder:
        alias: marvin255_jwt_symfony.encoder


    marvin255_jwt_symfony.decoder:
        class: Marvin255\Jwt\Decoder\Decoder
        arguments:
            - '@marvin255_jwt_symfony.builder'
    Marvin255\Jwt\JwtDecoder:
        alias: marvin255_jwt_symfony.decoder


    marvin255_jwt_symfony.validator:
        class: Marvin255\Jwt\Validator\Validator
    Marvin255\Jwt\JwtValidator:
        alias: marvin255_jwt_symfony.validator


    Marvin255\Jwt\Symfony\Profile\JwtProfileManager:
        class: Marvin255\Jwt\Symfony\Profile\JwtProfileManager
        arguments:
            - !tagged_iterator marvin255_jwt_symfony.registered_profiles
